resources:
  - name: foo
    type: qhode/GitRepo
    configuration:
      resourceFoo: 1
  - name: bar
    type: shippable/GitRepo
    syntaxVersion: 1.0.0
    configuration:
      name: test
  - name: secondres
    type: shippable/sampleResource
    syntaxVersion: latest
    configuration:
      resourceFoo: 1
  - name: gitrepores
    type: GitRepo
    configuration:
      path: bharath92/pipelines
      gitProvider: github
      branches:
        include: ^master$
  
pipelines:
  - name: sample_pipeline
    steps:
      - name: step0
        type: Bash
        configuration:
          inputSteps:
            - name: step0
          inputResources:
            - name: gitrepores
        execution:
         onStart:
           - echo lol
      - name: step1
        type: shippable/sampleStep
        configuration:
          inputResources:
            - name: foo
            - name: bar
            - name: gitrepores
          foo: lol
        execution:
          onStart:
            - get_resource_name --type GitRepo --operation IN
      - name: step2
        type: drydock/sampleStep
        configuration:
          inputSteps:
            - name: step1
          foo: test
          inputResources:
            - name: secondres
        execution:
          onSuccess:
            - node common/common.js
