# resources:
#   - name: foo
#     type: SampleResource
#     syntaxVersion: 1.0.0
#     configuration:
#       foo: bar
pipelines:
  - name: sample_pipeline
    steps:
      - name: health_check_1
        type: namespace/sampleStep
        syntaxVersion: latest
        configuration:
          # inputResources:
          #   - name: foo
          foo: lol
        execution:
          onStart:
            - node test.js
      # - name: health_check_2
      #   type: HealthCheck
      #   syntaxVersion: 0.0.2
      #   configuration:
      #     inputSteps:
      #       - name: health_check_1
      #     healthCheckUrl: https://api.github.com
      #     notifyOnSuccess: false
